// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcdhodvivroqrdnwdlcc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjZGhvZHZpdnJvcXJkbndkbGNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNTYxOTYsImV4cCI6MjA3MDczMjE5Nn0.2ssMjvtVJ3BeDG7_tRT0ykb2BjgEFrla55qfrdEcZzY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});